---
title: "Introduction to Deep Learning in R - Part 2"
author: "Evan"
date: "11/26/2018"
output: html_document
---


## Humans and dogs

### The data

Load a folder of human and dog images from the `data-raw` folder of the workshop materials and define the vector of `image_names` to be populated in a blank list named `images_list`. These free images were downloaded from [Burst](https://burst.shopify.com/):

Load code
```{r}
# 
train_path = "data-raw/dog-person/TRAIN"
val_path = "data-raw/dog-person/VAL"
train_images = list.files(train_path, full.names = T, recursive = T)
val_images = list.files(val_path, full.names = T, recursive = T)
length(train_images)
length(val_images)

#
ggdraw() + draw_image(train_images[1])
ggdraw() + draw_image(val_images[1])

# "chars" of our images.
img_width = img_height = 28L
batch_size = 5L
(num_train_samples = length(list.files(train_path, recursive = T)))
num_validation_samples = 10L
epochs = 50L

train_datagen = keras::image_data_generator(rescale = 1/255)

val_datagen = keras::image_data_generator(rescale = 1/255)

# 
train_gen =
  train_datagen$flow_from_directory(train_path,
                                    target_size = c(img_width, img_height),
                                    batch_size = batch_size,
                                    class_mode = "binary",
                                    color_mode = "grayscale")

# 
val_gen =
  val_datagen$flow_from_directory(val_path,
                                  target_size = c(img_width, img_height),
                                  batch_size = batch_size,
                                  class_mode = "binary",
                                  color_mode = "grayscale")

#train_datagen$flow(train_path, batch_size = 1)
```



## Define the model

```{r}
model <- keras_model_sequential() 
model %>% 
  layer_flatten(input_shape = c(img_width, img_height, 1)) %>%
  layer_dense(units = 256, activation = 'relu', input_shape = c(img_width, img_height)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 1, activation = 'sigmoid')
  
  
  # layer_dense(units = 60, activation = 'relu', input_shape = img_width * img_height) %>% 
  # layer_dropout(rate = 0.5) %>% 
  # layer_dense(units = 40, activation = 'relu') %>%
  # layer_dropout(rate = 0.25) %>%
  # layer_dense(units = 1, activation = 'sigmoid')
summary(model)
```

```{r}
model %>% compile(
  loss = 'binary_crossentropy',
  optimizer = optimizer_adam(),
  metrics = c('accuracy')
)
```


```{r}
# Train the model on the new data for a few epochs
history = model %>%
  fit_generator(train_gen,
                steps_per_epoch = as.integer(num_train_samples / batch_size),
                epochs = epochs,
                validation_data = val_gen,
                validation_steps = as.integer(num_validation_samples / batch_size))

# Review fitting history.
plot(history) + theme_bw()
```

```{r}
# CK: getting an error on this currently.
# "Error in py_call_impl(callable, dots$args, dots$keywords) : 
# ValueError: Error when checking target: expected dense_27 to have 2 dimensions, but got array with shape (20, 2, 2)"
model %>% evaluate(x_test, y_test)
```
